eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090/
  application:
    name: Plans
  profiles:
    active: development 
  config:
   import: optional:configserver:http://localhost:7070
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
